### PR TITLE
Feature/variables

### PR DESCRIPTION
**Pull request by mmaschenk**
Added a data directory with re-usable variables for pages. Added a 'basic guidelines' faq entry.

### CODE REVIEW

**Comment by sebranchett** [comment]
ERROR `/70-faq' not found
is back again. Missed a merge?

**Comment by mmaschenk** [comment]
Ehhhm. /70-faq should be gone, so that is not an error. Were do you see this error?

**Comment by mmaschenk** [comment]
@sebranchett : found the broken link and fixed it!

**Comment by mmaschenk** [comment]
Sorry to merge my own request: we needed to send out the mail to clients, and it needed a url...

**Pull request merged**
